[#_top]
= Development Getting Started
:toc:

== Configuration

include::development-configuration.adoc[tag=overview]

See <<development-configuration.adoc#_top, Development Configuration>> for more details.

=== Processing queue

Individual synchronization requests are processed in a queue (backed by ActiveMQ) with concurrency of one.
This ensures that no two synchronization threads might affect the same items (configure in application.yml).

See the IssuePoller as an entry point, which runs based on a CRON expression.
Found issues are then run through the SynchronizationFlowFactory, and for all issues with a matching flow, a SyncRequest is produced on the queue.

=== Processing a single issue

From a SyncRequest, an issue is derived, and the matching SynchronizationFlow is retrieved from the SynchronizationFlowFactory.
As described in <<syncFlowDefinitions,syncFlowDefinitions>>, a SynchronizationFlow can define an issue filter, and must define a collection of <<actionDefinitions,actionDefinitions>>.

. Load the source issue along with the key (=unique identifier) mapping.
This step also verifies that the "last updated" timestamp of the synchronization request matches that of the loaded issue (if not, a SynchronizationAbortedException is thrown).
. Locate a fitting sync flow, applying filters where defined.
. If one (1) sync flow is found, call that flow with the loaded issue.
.. If the flow cannot locate a target issue, and the flow doesn't define `defaultsForNewIssue`, a SynchronizationAbortedException is thrown.

=== Custom classes

The `settings.json` works with class FQNs, which must be present on the classpath, but not necessarily in this project.
If custom field mappers, filters etc. are needed, they can be provided in a separate JAR.
If those implementations might be of value to others, add them to this project in the `ch.loewenfels.issuetrackingsync.custom` package.

=== Controllers

The `DebugController` offers resources to access debug-relevant information from the tool while it is running.
See <<development-configuration.adoc#configUrl,configUrl>> and <<development-configuration.adoc#logsUrl,logsUrl>> for more information.

Logs and config can be accessed from the Admin page by means of the 'Show logs' and 'Show configuration' buttons.

== For contributors

This project aims at allowing for simple issue synchronization using a purely configurative approach, while also embracing proprietary extensions.
The latter can be defined using class FQNs in the settings.yml, and making sure the application finds the class on the classpath (but possibly outside this project's fat JAR).