[#_top]
= Development Getting Started
:toc:

== Build with RTC Client

To build the tool you need the IBM RTC Library.
This library is not in any open repository.
So you need to add it into your own repository or build path.
You can achieve this:

1. Download and install the Library from IBM.
Try to find the required libraries for the RTC-Client at: https://rsjazz.wordpress.com/
2. Add a mvn Repository to your local ~/.gradle/gradle.properties as the following parameter `repositoryIssueTrackingJars=&lt;URL_TO_MVN_REPO&gt;`.

To build the tool via Docker you need to supply the mvn Repository url.
Build and start the Docker image with the following commands:

[source,bash]
----
docker build --build-arg MVN_REPO=<URL_TO_MVN_REPO> -t issue-tracking-sync .
docker run -p 8080:8080 issue-tracking-sync
----

The other parameters have got useful default values:

[source,bash]
----
include::../../Dockerfile[tag=parameters]
----

== Configuration

include::development-configuration.adoc[tag=overview]

See <<development-configuration.adoc#_top, Development Configuration>> for more details.

=== Processing queue

Individual synchronization requests are processed in a queue (backed by ActiveMQ) with concurrency of one.
This ensures that no two synchronization threads might affect the same items (configure in application.yml).

See the IssuePoller as an entry point, which runs based on a CRON expression.
Found issues are then run through the SynchronizationFlowFactory, and for all issues with a matching flow, a SyncRequest is produced on the queue.

=== Processing a single issue

From a SyncRequest, an issue is derived, and the matching SynchronizationFlow is retrieved from the SynchronizationFlowFactory.
As described in <<syncFlowDefinitions,syncFlowDefinitions>>, a SynchronizationFlow can define an issue filter, and must define a collection of <<actionDefinitions,actionDefinitions>>.

. Load the source issue along with the key (=unique identifier) mapping.
This step also verifies that the "last updated" timestamp of the synchronization request matches that of the loaded issue (if not, a SynchronizationAbortedException is thrown).
. Locate a fitting sync flow, applying filters where defined.
. If one (1) sync flow is found, call that flow with the loaded issue.
.. If the flow cannot locate a target issue, and the flow doesn't define `defaultsForNewIssue`, a SynchronizationAbortedException is thrown.

=== Custom classes

The `settings.json` works with class FQNs, which must be present on the classpath, but not necessarily in this project.
If custom field mappers, filters etc. are needed, they can be provided in a separate JAR.
If those implementations might be of value to others, add them to this project in the `ch.loewenfels.issuetrackingsync.custom` package.

=== Controllers

The `DebugController` offers resources to access debug-relevant information from the tool while it is running.
Under `foobar.com/config` (while `foobar.com` is the issue-tracking-sync-tool) the `settings.json` can be accessed.
To ensure privacy, the default implementation masks passwords with asterisks.
Under `foobar.com/log` the log file of the tool can be downloaded.
This resource provides also a date-parameter for accessing past log files.
The date-parameter has the following pattern:
`yyyy-MM-dd`.
Hence, to access the log file from February 18<sup>th</sup> 2020, the URL would be `foobar.com/log2020-02-18`

== For contributors

This project aims at allowing for simple issue synchronization using a purely configurative approach, while also embracing proprietary extensions.
The latter can be defined using class FQNs in the settings.yml, and making sure the application finds the class on the classpath (but possibly outside this project's fat JAR).