= Field mappers

== DirectFieldMapper

This is the default field mapper which attempts to read the property `sourceName` and write it to `targetName`.

== HtmlToWikiFieldMapper

This mapper is useful for rich text fields which allow for markup in JIRA, and/or HTML in RTC (e.g. RTC 'description').

== CompoundStringFieldMapper

This mapper extends `HtmlToWikiFieldMapper` and can be used to map multiple text fields onto a single text field, and split it back.
It expects `associations` for each field definition except one (which will hold "the rest").

.Configuration to merge multiple fields:
[source,yaml]
----
  - sourceName: "ch.loewenfels.team.workitem.attribute.requirement,ch.loewenfels.team.workitem.attribute.defectdescription,ch.loewenfels.team.workitem.attribute.expected.conduct"
    targetName: description
    mapperClassname: ch.loewenfels.issuetrackingsync.executor.fields
    associations:
      "ch.loewenfels.team.workitem.attribute.defectdescription": "<h4>Error description</h4>"
      "ch.loewenfels.team.workitem.attribute.expected.conduct": "<h4>Expected behaviour</h4>"
----

.Configuration to split into multiple fields:
[source,yaml]
----
  - sourceName: description
    targetName: "ch.loewenfels.team.workitem.attribute.requirement,ch.loewenfels.team.workitem.attribute.defectdescription,ch.loewenfels.team.workitem.attribute.expected.conduct"
    mapperClassname: ch.loewenfels.issuetrackingsync.executor.fields
    associations:
      "ch.loewenfels.team.workitem.attribute.defectdescription": "<h4>Error description</h4>"
      "ch.loewenfels.team.workitem.attribute.expected.conduct": "<h4>Expected behaviour</h4>"
----

Note that the separator associations are in HTML, not in JIRA wiki markup.
This is due to the mapper extending HtmlToWikiFieldMapper, so it works internally with HTML.

== LinkToIssueFieldMapper

This mapper disregards the 'sourceName' and provides a link to the source issue.
It can be written to any 'targetName'.

== PriorityAndSeverityFieldMapper

This mapper is a slightly more complicated mapper, as JIRA typically knows 1 priority field, while RTC has a priority and severity.
This mapper uses the `associations`
as a matrix to map between these fields:

[source,yaml]
----
include::../../../framework/src/test/resources/settings.yml[tag=PriorityAndSeverityFieldMapper]
----

== MultiSelectionFieldMapper

For multi selection fields use this mapper.
It uses the `associations` as a matrix to map between these fields.
The following example shows a mapping from RTC to Jira:

[source,yaml]
----
include::../../../framework/src/test/resources/settings.yml[tag=MultiSelectionFieldMapper]
----

The opposite way, from Jira to RTC, would be as follows:

[source,yaml]
----
include::../../../framework/src/test/resources/settings.yml[tag=MultiSelectionFieldMapper-reversed]
----

== SingleSelectionFieldMapper

This mapper is similar like the above MultiSelectionFieldMapper: it also uses an `associations` matrix for mapping single selection fields between both clients.
The `association` matrix shall have the same structure as the above MultiSelectionFieldMapper.

== StatusFieldMapper

This mapper synchronizes state transitions, assuming that source and target client systems have a rough association between their resp. workflows:

1. Gets the current state of the source issue (`getValue`)
2. Gets the state changelog for the source issue (`getValue`)
3. Then, in `setValue` the source's changelog is used to locate the changelog entry which has a state matching the target issue's current state (using the fields association map to translate source states to target states)
4. For each changelog entry later than the one found in (1), retrieve the target state, seek a transition leading to that state, and transition the target issue

There are a few twists:

* JRJC easily provides available transitions for an issue via `jiraRestClient.issueClient.getTransitions(myIssue)`, but this contains no information on the target state of the transition.
Thus, the `AsynchronousHtmlRenderingRestClient` uses a JSON response from the API's /transitions response to find a suitable transition for a target state.
* If a source state changelog entry contains a state unknown in the target system, the state will not be synchronized.
* If the target system has multiple transitions for a single one on the source side, the field association can define a comma-separated list of target states.
