@startuml

title Level 1 view of IGS Change and Defect Synchronizer

cloud Loepa {
    package [igs-change-and-defect-synchronizer] as pi #ffd {}
    package [configuration] as pc #ffd {}
    package [jira-client] as pj #ffd {}
    package [rtc-client] as pr #ffd {}
    package [custom-mapper] as pm #ffd {}

    note top of pi : Project finally builds at Loepa
}

cloud GitHub as gh{
    package [issue-tracking-sync] as ps #ffd {
        package [framework] as fw #ffd {}
    }

    note top of ps : OS part build at GitHub
}

pi ..> pc

ps <. pi : all modules\ndepends on it
pj <.. pm
pr <.. pm

pi ..> pj
pi ..> pr
pi ..> pm


object atlassian #888
object rtc #888
pj ...> atlassian
pr ...> rtc

Caption All custom submodules are moved to Loepa

@enduml