name: doc-as-code

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install dot
        run: sudo apt-get install -y graphviz

      - name: Build with Gradle
        run: ./gradlew :documentation:asciidoctor

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: |
            documentation/build/docs
            !documentation/build/docs/.asciidoctor

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build/docs