name: additional jira-client

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew :jira-client:compileTestKotlin

      - name: Build with Gradle
        run: ./gradlew :jira-client:test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jira-client-test-reports
          path: jira-client/build/reports
